services:
  github-actions-runner:
    image: zvesdochyot/github-actions-runner:latest
    container_name: github-actions-runner
    environment:
      RUNNER_TYPE:
      ORGANIZATION_NAME:
      OWNER:
      REPOSITORY:
      ACCESS_TOKEN:
      API_VERSION:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /actions-runner/running:/actions-runner/running:rw
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 8G
