services:
  github-actions-runner:
    image: zvesdochyot/github-actions-runner:latest
    environment:
    - ORGANIZATION_NAME=
    - ACCESS_TOKEN=
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /srv/docker/runners:/home/runner-user/actions-runner/_work
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 4G
